### ISSUE TITLE
Fix CI caching

### ISSUE THREAD

**Issue by PatrickDeVries** [yobgob/too-many-hooks#55]
`c-hive/gha-yarn-cache@v2` is deprecated and subsumed by [setup-node](https://github.com/actions/setup-node) but we are currently using both

**Comment by dawsonbooth** [comment]
Related links:
- https://github.com/c-hive/gha-yarn-cache#deprecated
- https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
- https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
