### ISSUE TITLE
Add contributors/credits section to README

### ISSUE THREAD

**Issue by dawsonbooth** [yobgob/too-many-hooks#56]
Use an existing action to generate a list of contributors based on commit history

e.g. https://github.com/all-contributors/all-contributors

**Comment by BT-H** [comment]
I'd be glad to help if you assign it to me.

**Comment by dawsonbooth** [comment]
Great, thanks! You’ve been assigned

**Comment by BT-H** [comment]
I'm newer at coding so I just want to check that I understand the task before proceeding:
I should take the .all-contributorsrc JSON file that is created by the All Contributors Bot and then reconfigure the bot to update the files in Readme.MD?

**Comment by dawsonbooth** [comment]
After looking into it a little further, we probably don't need something as verbose as [all-contributors](https://github.com/all-contributors/all-contributors). Let's just stick an auto-updated image in the README using something like [contrib.rocks](https://contrib.rocks/), which generates a contributors image automatically.

Here's a [step-by-step guide ](https://levelup.gitconnected.com/displaying-contributors-image-on-readme-files-with-no-pain-f1cbaca963e8)I found. Let me know if you have any questions!

**Comment by BT-H** [comment]
Sounds good! I'm on it.

**Comment by PatrickDeVries** [comment]
Any updates? Should we reassign this? @BT-H

**Comment by jon3b** [comment]
Since this has been stale for a few months I'll pick it up
